/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './route/__root'
import { Route as LayoutRouteRouteImport } from './route/_layout/route'
import { Route as LayoutTransIndexRouteImport } from './route/_layout/trans/index'
import { Route as LayoutNoteIndexRouteImport } from './route/_layout/note/index'
import { Route as LayoutDocsIndexRouteImport } from './route/_layout/docs/index'
import { Route as LayoutBoardIndexRouteImport } from './route/_layout/board/index'
import { Route as LayouthomeIndexRouteImport } from './route/_layout/(home)/index'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTransIndexRoute = LayoutTransIndexRouteImport.update({
  id: '/trans/',
  path: '/trans/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutNoteIndexRoute = LayoutNoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutBoardIndexRoute = LayoutBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayouthomeIndexRoute = LayouthomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayouthomeIndexRoute
  '/board/': typeof LayoutBoardIndexRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/note/': typeof LayoutNoteIndexRoute
  '/trans/': typeof LayoutTransIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayouthomeIndexRoute
  '/board': typeof LayoutBoardIndexRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/note': typeof LayoutNoteIndexRoute
  '/trans': typeof LayoutTransIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/(home)/': typeof LayouthomeIndexRoute
  '/_layout/board/': typeof LayoutBoardIndexRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/note/': typeof LayoutNoteIndexRoute
  '/_layout/trans/': typeof LayoutTransIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board/' | '/docs/' | '/note/' | '/trans/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/docs' | '/note' | '/trans'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/(home)/'
    | '/_layout/board/'
    | '/_layout/docs/'
    | '/_layout/note/'
    | '/_layout/trans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/trans/': {
      id: '/_layout/trans/'
      path: '/trans'
      fullPath: '/trans/'
      preLoaderRoute: typeof LayoutTransIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/note/': {
      id: '/_layout/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof LayoutNoteIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/board/': {
      id: '/_layout/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof LayoutBoardIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(home)/': {
      id: '/_layout/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayouthomeIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayouthomeIndexRoute: typeof LayouthomeIndexRoute
  LayoutBoardIndexRoute: typeof LayoutBoardIndexRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
  LayoutNoteIndexRoute: typeof LayoutNoteIndexRoute
  LayoutTransIndexRoute: typeof LayoutTransIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayouthomeIndexRoute: LayouthomeIndexRoute,
  LayoutBoardIndexRoute: LayoutBoardIndexRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
  LayoutNoteIndexRoute: LayoutNoteIndexRoute,
  LayoutTransIndexRoute: LayoutTransIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
